#!/usr/bin/env python

import findrox; findrox.version(2, 0, 0)
import rox, os, sys

try:
	__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))
	
	if len(sys.argv) > 1:
		import Wifi
		Wifi.Wifi(sys.argv[1])
	else:
		rox.info(_("This is a panel applet.  Drag it to your panel to run it.\nI'll now let you edit the configuration options..."))
		import Wifi
		rox.edit_options()
	rox.mainloop()
except:
	rox.report_exception()
